name: "Shared Master Workflow"

on:
  push:
    branches: ["master", "development"]
  pull_request:
    branches: [ "master", "development" ]
  workflow_dispatch:

jobs:
  master-workflow:
    uses: gqcorneby/workflows/.github/workflows/master.yml@main
    with:
      languages: "javascript-typescript"
      build_mode: "none"
    secrets: inherit
