name: "Shared Master Workflow"

on:
  push:
    branches: ["master", "development"]
  pull_request:
    branches: [ "master", "development" ]
  workflow_dispatch:

jobs:
  master-workflow:
    uses: EyeSeeTea/github-workflows/.github/workflows/master.yml@master


  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Paths
        run: |
          echo "Current directory: $(pwd)"
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          ls -lah "$(dirname "${GITHUB_ACTION_PATH}")"

